version: '3.8'

volumes:
  bundle:
  postgres-data:
services:
  roda:
    build: .
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle
    ports:
      - "3001:3000"
    env_file:
      - .env
    stdin_open: true
    tty: true
  db:
    image: postgres:alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - postgres-data:/var/lib/postgresql/data
